import * as fs from "fs";

const dotFile = fs.readFileSync("./northwind.dot").toString();

interface IRegexpMap {
    [key: string]: [RegExp, string];
}

const regexpMap: IRegexpMap = {
    label: [/"\\nGenerated by SchemaSpy"/g, '""'],
    relationType: [/<TD ALIGN="RIGHT">\[table\]<\/TD>/, ""],
    primaryKeys: [/<IMG SRC="\.\.\/\.\.\/images\/primaryKeys\.png"\/>/gi, '<TD ALIGN="LEFT">[table]</TD>'],
};

const parser = (dotFile: string, regexpMap: IRegexpMap) => {
    for (let [regexp, replacement] of Object.values(regexpMap)) {
        dotFile = dotFile.replace(regexp, replacement);
    }
    return dotFile;
};

const parsedFile = parser(dotFile, regexpMap);

fs.writeFileSync("./parsed.dot", parsedFile);
